version: '3.7'
services:
  db:
    container_name: test_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
      POSTGRES_USER: root
    ports:
      - '5432:5432'
